spring.application.name=ticket-booking-system

spring.datasource.url=jdbc:postgresql://ticket-db:5432/ticketdb
spring.datasource.username=postgres
spring.datasource.password=2004

server.port=8083

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mysecretkeymysecretkeymysecretkey123


spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000