server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This line redirects all 404s to index.html so React can take over
        try_files $uri $uri/ /index.html;
    }

    # Optional: Handles errors for the backend API if needed
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}